services:
  - type: worker
    name: scrap3r-mcp-trader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m main
    envVars:
      - key: ALPACA_KEY
        sync: false
      - key: ALPACA_SECRET
        sync: false
      - key: PYTHONPATH
        value: /opt/render/project/src
        
  - type: web
    name: scrap3r-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python web_dashboard.py
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src